name: 'Run Tests and Code Analysis'
description: 'GitHub Composite Action to Run Tests and Code Analysis'
inputs:
  source-code-folder-name:
    description: 'pylint and Bandit Analysis Source code base path'
    required: true
    default: 'src'  
runs:
  using: "composite"
  steps:
  - id: install-dependencies
    run: |
      python -m pip install --upgrade pip
      mkdir -p reports
      pip install tox pylint bandit
    shell: bash
  - id: runt-tests-with-tox
    run: |      
      tox
    shell: bash
  - id: run-bandit
    run: |
      bandit -r ${{ inputs.source-code-folder-name }} -f json -o reports/bandit.json || true
    shell: bash
  - name: run-pylint
    id: |
      pylint ${{ inputs.source-code-folder-name }} -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylint.out
    shell: bash
