name: 'Run Tests and Code Analysis'
description: 'GitHub Composite Action to Run Tests and Code Analysis'
inputs:
  source-code-folder-name:
    description: 'pylint and Bandit Analysis Source code base path'
    required: true 
runs:
  using: "composite"
  steps:
  - id: install-dependencies
    run: |
      python -m pip install pip==20.2.4
      mkdir -p reports
      pip install "tox>=3,<4" "pylint>=2,<3" "bandit>=1,<2"
    shell: bash
  - id: runt-tests-with-tox
    run: |      
      tox
    shell: bash
  - id: run-bandit
    run: |
      bandit -r ${{ inputs.source-code-folder-name }} -f json -o reports/bandit.json || true
    shell: bash
  - id: run-pylint
    run: |
      pylint ${{ inputs.source-code-folder-name }} -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > pylint.out
    shell: bash
